### ISSUE TITLE
Unsetting "title" attribute in JSON links

### ISSUE THREAD

**Issue by acleon** [blongden/hal#41]
When creating a HAL object using the JSON factory, it unsets the "title" attribute:

https://github.com/blongden/hal/blob/develop/src/Nocarrier/JsonHalFactory.php#L62

There's no indication why it does this, and from what I can see in the XML factory, it doesn't do the equivalent. Should a comment be added to clarify why?

**Comment by blongden** [comment]
Good question. Let me dig back and see if I can remember / work out why that was...

**Comment by blongden** [comment]
I've removed this from the master branch. I can only imagine that this was a relic from an old idea. There's no reason I can think of as to why it unsets it!

**Comment by acleon** [comment]
Nice one. Thanks for your effort on this library - much appreciated.
