### ISSUE TITLE
Needs a unit test for getFirstLink

### ISSUE THREAD

**Issue by blongden** [blongden/hal#46]
PR #45 didn't come with a unit test. It could use one.

**Comment by dazz** [comment]
@blongden test has been written :) do you think this is enough or are more cases needed?

**Comment by blongden** [comment]
Perfect! Thank you :)

:+1:

**Comment by dazz** [comment]
:dancers: Thank you very much! Could I bother you for creating a new release?

**Comment by blongden** [comment]
There you go - 0.9.11 released! :)

**Comment by dazz** [comment]
Awesome! Thanks for you help!
